version: "3.8"
services:
  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - NODE_ENV=production
  # depends_on:
  #   - db
