services:
  client:
    image: ghcr.io/razikdontcare/wefoundit-client:latest
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    image: ghcr.io/razikdontcare/wefoundit-server:latest
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - FIREBASE_APIKEY=${FIREBASE_APIKEY}
      - FIREBASE_AUTHDOMAIN=${FIREBASE_AUTHDOMAIN}
      - FIREBASE_PROJECTID=${FIREBASE_PROJECTID}
      - FIREBASE_STORAGEBUCKET=${FIREBASE_STORAGEBUCKET}
      - FIREBASE_MESSAGINGSENDERID=${FIREBASE_MESSAGINGSENDERID}
      - FIREBASE_APPID=${FIREBASE_APPID}
      - FIREBASE_MEASUREMENTID=${FIREBASE_MEASUREMENTID}
      - ADMIN_CLIENTEMAIL=${ADMIN_CLIENTEMAIL}
      - ADMIN_PRIVATEKEY=${ADMIN_PRIVATEKEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
