services:
  client:
    image: ghcr.io/razikdontcare/wefoundit-client-dev:latest
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    image: ghcr.io/razikdontcare/wefoundit-server-dev:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
