services:
  client:
    image: ghcr.io/razikdontcare/wefoundit-client:latest
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    image: ghcr.io/razikdontcare/wefoundit-server:latest
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
