openapi: 3.0.0
info:
  title: WeFoundIt API
  version: 1.0.0
  description: API documentation for WeFoundIt backend
servers:
  - url: http://localhost:5000
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        "200":
          description: API is running
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
  /api/search:
    get:
      summary: Search reports
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: Search query
        - in: query
          name: jenis_lap
          schema:
            type: string
            enum: [kehilangan, penemuan]
          required: false
          description: Type of report
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseArray"
        "400":
          description: Missing query parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
  /api/auth:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
  /api/auth/register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        "201":
          description: Registration successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
  /api/reports:
    get:
      summary: Get all reports
      responses:
        "200":
          description: List of reports
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseArray"
    post:
      summary: Create a new report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                jenis_lap:
                  type: string
                  enum: [kehilangan, penemuan]
      responses:
        "201":
          description: Report created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseNull"
components:
  schemas:
    ApiResponseNull:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: "null"
    ApiResponseArray:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: array
          items:
            type: object
